<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \AppBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'cemeteries', 'products', 'created_user_products', 'created_code_groups', 'created_credentials', 'created_order_products', 'created_page_categories', 'created_page_types', 'created_product_categories', 'created_product_connections', 'created_product_types', 'created_payments', 'created_status_histories', 'created_messages', 'recived_messages', 'updated_messages', 'created_groups', 'created_posts', 'created_mails', 'created_products', 'created_order_statuses', 'pages', 'created_pages', 'credentials', 'cart', 'orders', 'created_orders', 'parent_partner_orders', 'partner_orders', 'created_addresses', 'contracted_orders', 'families', 'first_name', 'last_name', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'phone', 'billing_address', 'delivery_address', 'type', 'registration_token', 'notification_order', 'invoice', 'ads', 'ads_show', 'ads_name', 'ads_description', 'ad_mobile', 'ad_desktop', 'ad_link', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'locale', 'file', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'path', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'description', 'discount', 'provision', 'rating', 'cities', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'facebook_id', 'notification_message', 'notification_post', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'updated', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'deleted', 'created_users', 'creator', 'partners', 'parent_partner', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'parent_partner_code', 'username', 'usernameCanonical', 'email', 'emailCanonical', 'enabled', 'salt', 'password', 'plainPassword', 'lastLogin', 'confirmationToken', 'passwordRequestedAt', 'groups', 'locked', 'expired', 'expiresAt', 'roles', 'credentialsExpired', 'credentialsExpireAt'];
        }

        return ['__isInitialized__', 'id', 'cemeteries', 'products', 'created_user_products', 'created_code_groups', 'created_credentials', 'created_order_products', 'created_page_categories', 'created_page_types', 'created_product_categories', 'created_product_connections', 'created_product_types', 'created_payments', 'created_status_histories', 'created_messages', 'recived_messages', 'updated_messages', 'created_groups', 'created_posts', 'created_mails', 'created_products', 'created_order_statuses', 'pages', 'created_pages', 'credentials', 'cart', 'orders', 'created_orders', 'parent_partner_orders', 'partner_orders', 'created_addresses', 'contracted_orders', 'families', 'first_name', 'last_name', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'phone', 'billing_address', 'delivery_address', 'type', 'registration_token', 'notification_order', 'invoice', 'ads', 'ads_show', 'ads_name', 'ads_description', 'ad_mobile', 'ad_desktop', 'ad_link', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'locale', 'file', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'path', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'description', 'discount', 'provision', 'rating', 'cities', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'facebook_id', 'notification_message', 'notification_post', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'updated', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'deleted', 'created_users', 'creator', 'partners', 'parent_partner', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'parent_partner_code', 'username', 'usernameCanonical', 'email', 'emailCanonical', 'enabled', 'salt', 'password', 'plainPassword', 'lastLogin', 'confirmationToken', 'passwordRequestedAt', 'groups', 'locked', 'expired', 'expiresAt', 'roles', 'credentialsExpired', 'credentialsExpireAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailCanonical($emailCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailCanonical', [$emailCanonical]);

        return parent::setEmailCanonical($emailCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function havePagePermission($page, $type = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'havePagePermission', [$page, $type]);

        return parent::havePagePermission($page, $type);
    }

    /**
     * {@inheritDoc}
     */
    public function haveFamilyPermission($family, $type = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'haveFamilyPermission', [$family, $type]);

        return parent::haveFamilyPermission($family, $type);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermissionTypes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermissionTypes', []);

        return parent::getPermissionTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function getPermissionType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermissionType', [$type]);

        return parent::getPermissionType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceTypes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceTypes', []);

        return parent::getInvoiceTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceType', [$type]);

        return parent::getInvoiceType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoicePrefixes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoicePrefixes', []);

        return parent::getInvoicePrefixes();
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoicePrefix($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoicePrefix', [$type]);

        return parent::getInvoicePrefix($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceTaxes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceTaxes', []);

        return parent::getInvoiceTaxes();
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceTax($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceTax', [$type]);

        return parent::getInvoiceTax($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceTaxRates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceTaxRates', []);

        return parent::getInvoiceTaxRates();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeName', []);

        return parent::getTypeName();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeNames', []);

        return parent::getTypeNames();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPath($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPath', [$path]);

        return parent::setPath($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', []);

        return parent::getPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvatar($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvatar', [$path]);

        return parent::setAvatar($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatar', []);

        return parent::getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', [$file]);

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', []);

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpload', []);

        return parent::preUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', []);

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function storeFilenameForRemove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'storeFilenameForRemove', []);

        return parent::storeFilenameForRemove();
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpload', []);

        return parent::removeUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', []);

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', []);

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadRootDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadRootDir', []);

        return parent::getUploadRootDir();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', [$updated]);

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', []);

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', [$firstName]);

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', []);

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', [$lastName]);

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', []);

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function getFullName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullName', []);

        return parent::getFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotificationStockAlert($notificationStockAlert)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotificationStockAlert', [$notificationStockAlert]);

        return parent::setNotificationStockAlert($notificationStockAlert);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotificationStockAlert()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotificationStockAlert', []);

        return parent::getNotificationStockAlert();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotificationOrder($notificationOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotificationOrder', [$notificationOrder]);

        return parent::setNotificationOrder($notificationOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotificationOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotificationOrder', []);

        return parent::getNotificationOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartnerContact($partnerContact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartnerContact', [$partnerContact]);

        return parent::setPartnerContact($partnerContact);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartnerContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartnerContact', []);

        return parent::getPartnerContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistrationToken($registrationToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistrationToken', [$registrationToken]);

        return parent::setRegistrationToken($registrationToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationToken', []);

        return parent::getRegistrationToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddress(\AppBundle\Entity\Address $billingAddress = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddress', [$billingAddress]);

        return parent::setBillingAddress($billingAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress', []);

        return parent::getBillingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryAddress(\AppBundle\Entity\Address $deliveryAddress = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryAddress', [$deliveryAddress]);

        return parent::setDeliveryAddress($deliveryAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryAddress', []);

        return parent::getDeliveryAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocale', [$locale]);

        return parent::setLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocale', []);

        return parent::getLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(\AppBundle\Entity\Country $country = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoice($invoice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoice', [$invoice]);

        return parent::setInvoice($invoice);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoice', []);

        return parent::getInvoice();
    }

    /**
     * {@inheritDoc}
     */
    public function addCemetery(\AppBundle\Entity\Cemetery $cemetery)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCemetery', [$cemetery]);

        return parent::addCemetery($cemetery);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCemetery(\AppBundle\Entity\Cemetery $cemetery)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCemetery', [$cemetery]);

        return parent::removeCemetery($cemetery);
    }

    /**
     * {@inheritDoc}
     */
    public function getCemeteries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCemeteries', []);

        return parent::getCemeteries();
    }

    /**
     * {@inheritDoc}
     */
    public function addFamily(\AppBundle\Entity\Family $family)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFamily', [$family]);

        return parent::addFamily($family);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFamily(\AppBundle\Entity\Family $family)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFamily', [$family]);

        return parent::removeFamily($family);
    }

    /**
     * {@inheritDoc}
     */
    public function getFamilies()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFamilies', []);

        return parent::getFamilies();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebookId($facebookId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebookId', [$facebookId]);

        return parent::setFacebookId($facebookId);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebookId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebookId', []);

        return parent::getFacebookId();
    }

    /**
     * {@inheritDoc}
     */
    public function addContractedOrder(\AppBundle\Entity\OrderProduct $contractedOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContractedOrder', [$contractedOrder]);

        return parent::addContractedOrder($contractedOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContractedOrder(\AppBundle\Entity\OrderProduct $contractedOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContractedOrder', [$contractedOrder]);

        return parent::removeContractedOrder($contractedOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getContractedOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContractedOrders', []);

        return parent::getContractedOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function addPage(\AppBundle\Entity\Page $page)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPage', [$page]);

        return parent::addPage($page);
    }

    /**
     * {@inheritDoc}
     */
    public function removePage(\AppBundle\Entity\Page $page)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePage', [$page]);

        return parent::removePage($page);
    }

    /**
     * {@inheritDoc}
     */
    public function getPages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPages', []);

        return parent::getPages();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrder(\AppBundle\Entity\Order $order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrder', [$order]);

        return parent::addOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrder(\AppBundle\Entity\Order $order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrder', [$order]);

        return parent::removeOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrders', []);

        return parent::getOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', [$deleted]);

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', []);

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator(\AppBundle\Entity\User $creator = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', [$creator]);

        return parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', []);

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotificationMessage($notificationMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotificationMessage', [$notificationMessage]);

        return parent::setNotificationMessage($notificationMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotificationMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotificationMessage', []);

        return parent::getNotificationMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotificationPost($notificationPost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotificationPost', [$notificationPost]);

        return parent::setNotificationPost($notificationPost);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotificationPost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotificationPost', []);

        return parent::getNotificationPost();
    }

    /**
     * {@inheritDoc}
     */
    public function setCart(\AppBundle\Entity\Order $cart = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCart', [$cart]);

        return parent::setCart($cart);
    }

    /**
     * {@inheritDoc}
     */
    public function getCart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCart', []);

        return parent::getCart();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', [$phone]);

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', []);

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setRating($rating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating', [$rating]);

        return parent::setRating($rating);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating', []);

        return parent::getRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setCities($cities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCities', [$cities]);

        return parent::setCities($cities);
    }

    /**
     * {@inheritDoc}
     */
    public function getCities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCities', []);

        return parent::getCities();
    }

    /**
     * {@inheritDoc}
     */
    public function addCredential(\AppBundle\Entity\PageCredentials $credential)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCredential', [$credential]);

        return parent::addCredential($credential);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCredential(\AppBundle\Entity\PageCredentials $credential)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCredential', [$credential]);

        return parent::removeCredential($credential);
    }

    /**
     * {@inheritDoc}
     */
    public function getCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredentials', []);

        return parent::getCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscount($discount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscount', [$discount]);

        return parent::setDiscount($discount);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscount', []);

        return parent::getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduct(\AppBundle\Entity\UserProduct $product)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduct', [$product]);

        return parent::addProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduct(\AppBundle\Entity\UserProduct $product)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduct', [$product]);

        return parent::removeProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducts', []);

        return parent::getProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedUserProduct(\AppBundle\Entity\UserProduct $createdUserProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedUserProduct', [$createdUserProduct]);

        return parent::addCreatedUserProduct($createdUserProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedUserProduct(\AppBundle\Entity\UserProduct $createdUserProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedUserProduct', [$createdUserProduct]);

        return parent::removeCreatedUserProduct($createdUserProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedUserProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedUserProducts', []);

        return parent::getCreatedUserProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedCodeGroup(\AppBundle\Entity\CodeGroup $createdCodeGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedCodeGroup', [$createdCodeGroup]);

        return parent::addCreatedCodeGroup($createdCodeGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedCodeGroup(\AppBundle\Entity\CodeGroup $createdCodeGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedCodeGroup', [$createdCodeGroup]);

        return parent::removeCreatedCodeGroup($createdCodeGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedCodeGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedCodeGroups', []);

        return parent::getCreatedCodeGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedCredential(\AppBundle\Entity\PageCredentials $createdCredential)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedCredential', [$createdCredential]);

        return parent::addCreatedCredential($createdCredential);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedCredential(\AppBundle\Entity\PageCredentials $createdCredential)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedCredential', [$createdCredential]);

        return parent::removeCreatedCredential($createdCredential);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedCredentials', []);

        return parent::getCreatedCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedOrderProduct(\AppBundle\Entity\OrderProduct $createdOrderProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedOrderProduct', [$createdOrderProduct]);

        return parent::addCreatedOrderProduct($createdOrderProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedOrderProduct(\AppBundle\Entity\OrderProduct $createdOrderProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedOrderProduct', [$createdOrderProduct]);

        return parent::removeCreatedOrderProduct($createdOrderProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOrderProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOrderProducts', []);

        return parent::getCreatedOrderProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedPageCategory(\AppBundle\Entity\PageCategory $createdPageCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedPageCategory', [$createdPageCategory]);

        return parent::addCreatedPageCategory($createdPageCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedPageCategory(\AppBundle\Entity\PageCategory $createdPageCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedPageCategory', [$createdPageCategory]);

        return parent::removeCreatedPageCategory($createdPageCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedPageCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedPageCategories', []);

        return parent::getCreatedPageCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedPageType(\AppBundle\Entity\PageType $createdPageType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedPageType', [$createdPageType]);

        return parent::addCreatedPageType($createdPageType);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedPageType(\AppBundle\Entity\PageType $createdPageType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedPageType', [$createdPageType]);

        return parent::removeCreatedPageType($createdPageType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedPageTypes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedPageTypes', []);

        return parent::getCreatedPageTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedProductCategory(\AppBundle\Entity\ProductCategory $createdProductCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedProductCategory', [$createdProductCategory]);

        return parent::addCreatedProductCategory($createdProductCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedProductCategory(\AppBundle\Entity\ProductCategory $createdProductCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedProductCategory', [$createdProductCategory]);

        return parent::removeCreatedProductCategory($createdProductCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedProductCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedProductCategories', []);

        return parent::getCreatedProductCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedProductConnection(\AppBundle\Entity\ProductConnection $createdProductConnection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedProductConnection', [$createdProductConnection]);

        return parent::addCreatedProductConnection($createdProductConnection);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedProductConnection(\AppBundle\Entity\ProductConnection $createdProductConnection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedProductConnection', [$createdProductConnection]);

        return parent::removeCreatedProductConnection($createdProductConnection);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedProductConnections()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedProductConnections', []);

        return parent::getCreatedProductConnections();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedProductType(\AppBundle\Entity\ProductType $createdProductType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedProductType', [$createdProductType]);

        return parent::addCreatedProductType($createdProductType);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedProductType(\AppBundle\Entity\ProductType $createdProductType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedProductType', [$createdProductType]);

        return parent::removeCreatedProductType($createdProductType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedProductTypes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedProductTypes', []);

        return parent::getCreatedProductTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedPayment(\AppBundle\Entity\Payment $createdPayment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedPayment', [$createdPayment]);

        return parent::addCreatedPayment($createdPayment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedPayment(\AppBundle\Entity\Payment $createdPayment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedPayment', [$createdPayment]);

        return parent::removeCreatedPayment($createdPayment);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedPayments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedPayments', []);

        return parent::getCreatedPayments();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedStatusHistory(\AppBundle\Entity\OrderStatusHistory $createdStatusHistory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedStatusHistory', [$createdStatusHistory]);

        return parent::addCreatedStatusHistory($createdStatusHistory);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedStatusHistory(\AppBundle\Entity\OrderStatusHistory $createdStatusHistory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedStatusHistory', [$createdStatusHistory]);

        return parent::removeCreatedStatusHistory($createdStatusHistory);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedStatusHistories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedStatusHistories', []);

        return parent::getCreatedStatusHistories();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedMessage(\AppBundle\Entity\Message $createdMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedMessage', [$createdMessage]);

        return parent::addCreatedMessage($createdMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedMessage(\AppBundle\Entity\Message $createdMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedMessage', [$createdMessage]);

        return parent::removeCreatedMessage($createdMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedMessages', []);

        return parent::getCreatedMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function addRecivedMessage(\AppBundle\Entity\Message $recivedMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRecivedMessage', [$recivedMessage]);

        return parent::addRecivedMessage($recivedMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRecivedMessage(\AppBundle\Entity\Message $recivedMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRecivedMessage', [$recivedMessage]);

        return parent::removeRecivedMessage($recivedMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecivedMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecivedMessages', []);

        return parent::getRecivedMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function addUpdatedMessage(\AppBundle\Entity\Message $updatedMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUpdatedMessage', [$updatedMessage]);

        return parent::addUpdatedMessage($updatedMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpdatedMessage(\AppBundle\Entity\Message $updatedMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpdatedMessage', [$updatedMessage]);

        return parent::removeUpdatedMessage($updatedMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedMessages', []);

        return parent::getUpdatedMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedGroup(\AppBundle\Entity\Group $createdGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedGroup', [$createdGroup]);

        return parent::addCreatedGroup($createdGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedGroup(\AppBundle\Entity\Group $createdGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedGroup', [$createdGroup]);

        return parent::removeCreatedGroup($createdGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedGroups', []);

        return parent::getCreatedGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedPost(\AppBundle\Entity\Post $createdPost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedPost', [$createdPost]);

        return parent::addCreatedPost($createdPost);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedPost(\AppBundle\Entity\Post $createdPost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedPost', [$createdPost]);

        return parent::removeCreatedPost($createdPost);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedPosts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedPosts', []);

        return parent::getCreatedPosts();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedMail(\AppBundle\Entity\Mail $createdMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedMail', [$createdMail]);

        return parent::addCreatedMail($createdMail);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedMail(\AppBundle\Entity\Mail $createdMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedMail', [$createdMail]);

        return parent::removeCreatedMail($createdMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedMails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedMails', []);

        return parent::getCreatedMails();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedProduct(\AppBundle\Entity\Product $createdProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedProduct', [$createdProduct]);

        return parent::addCreatedProduct($createdProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedProduct(\AppBundle\Entity\Product $createdProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedProduct', [$createdProduct]);

        return parent::removeCreatedProduct($createdProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedProducts', []);

        return parent::getCreatedProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedOrderStatus(\AppBundle\Entity\OrderStatus $createdOrderStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedOrderStatus', [$createdOrderStatus]);

        return parent::addCreatedOrderStatus($createdOrderStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedOrderStatus(\AppBundle\Entity\OrderStatus $createdOrderStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedOrderStatus', [$createdOrderStatus]);

        return parent::removeCreatedOrderStatus($createdOrderStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOrderStatuses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOrderStatuses', []);

        return parent::getCreatedOrderStatuses();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedPage(\AppBundle\Entity\Page $createdPage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedPage', [$createdPage]);

        return parent::addCreatedPage($createdPage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedPage(\AppBundle\Entity\Page $createdPage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedPage', [$createdPage]);

        return parent::removeCreatedPage($createdPage);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedPages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedPages', []);

        return parent::getCreatedPages();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedOrder(\AppBundle\Entity\Order $createdOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedOrder', [$createdOrder]);

        return parent::addCreatedOrder($createdOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedOrder(\AppBundle\Entity\Order $createdOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedOrder', [$createdOrder]);

        return parent::removeCreatedOrder($createdOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOrders', []);

        return parent::getCreatedOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedAddress(\AppBundle\Entity\Address $createdAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedAddress', [$createdAddress]);

        return parent::addCreatedAddress($createdAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedAddress(\AppBundle\Entity\Address $createdAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedAddress', [$createdAddress]);

        return parent::removeCreatedAddress($createdAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAddresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAddresses', []);

        return parent::getCreatedAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedUser(\AppBundle\Entity\User $createdUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedUser', [$createdUser]);

        return parent::addCreatedUser($createdUser);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedUser(\AppBundle\Entity\User $createdUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedUser', [$createdUser]);

        return parent::removeCreatedUser($createdUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedUsers', []);

        return parent::getCreatedUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvision($provision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvision', [$provision]);

        return parent::setProvision($provision);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvision', []);

        return parent::getProvision();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentPartnerCode($parentPartnerCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentPartnerCode', [$parentPartnerCode]);

        return parent::setParentPartnerCode($parentPartnerCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentPartnerCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentPartnerCode', []);

        return parent::getParentPartnerCode();
    }

    /**
     * {@inheritDoc}
     */
    public function addParentPartnerOrder(\AppBundle\Entity\Order $parentPartnerOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParentPartnerOrder', [$parentPartnerOrder]);

        return parent::addParentPartnerOrder($parentPartnerOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParentPartnerOrder(\AppBundle\Entity\Order $parentPartnerOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParentPartnerOrder', [$parentPartnerOrder]);

        return parent::removeParentPartnerOrder($parentPartnerOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentPartnerOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentPartnerOrders', []);

        return parent::getParentPartnerOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function addPartner(\AppBundle\Entity\User $partner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPartner', [$partner]);

        return parent::addPartner($partner);
    }

    /**
     * {@inheritDoc}
     */
    public function removePartner(\AppBundle\Entity\User $partner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePartner', [$partner]);

        return parent::removePartner($partner);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartners()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartners', []);

        return parent::getPartners();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentPartner(\AppBundle\Entity\User $parentPartner = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentPartner', [$parentPartner]);

        return parent::setParentPartner($parentPartner);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentPartner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentPartner', []);

        return parent::getParentPartner();
    }

    /**
     * {@inheritDoc}
     */
    public function addPartnerOrder(\AppBundle\Entity\Order $partnerOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPartnerOrder', [$partnerOrder]);

        return parent::addPartnerOrder($partnerOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function removePartnerOrder(\AppBundle\Entity\Order $partnerOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePartnerOrder', [$partnerOrder]);

        return parent::removePartnerOrder($partnerOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartnerOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartnerOrders', []);

        return parent::getPartnerOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function setAds($ads)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAds', [$ads]);

        return parent::setAds($ads);
    }

    /**
     * {@inheritDoc}
     */
    public function getAds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAds', []);

        return parent::getAds();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdsShow($adsShow)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdsShow', [$adsShow]);

        return parent::setAdsShow($adsShow);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdsShow()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdsShow', []);

        return parent::getAdsShow();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdsName($adsName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdsName', [$adsName]);

        return parent::setAdsName($adsName);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdsName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdsName', []);

        return parent::getAdsName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdsDescription($adsDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdsDescription', [$adsDescription]);

        return parent::setAdsDescription($adsDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdsDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdsDescription', []);

        return parent::getAdsDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdMobile($adMobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdMobile', [$adMobile]);

        return parent::setAdMobile($adMobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdMobile', []);

        return parent::getAdMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdDesktop($adDesktop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdDesktop', [$adDesktop]);

        return parent::setAdDesktop($adDesktop);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdDesktop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdDesktop', []);

        return parent::getAdDesktop();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdLink($adLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdLink', [$adLink]);

        return parent::setAdLink($adLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdLink', []);

        return parent::getAdLink();
    }

    /**
     * {@inheritDoc}
     */
    public function addRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', [$role]);

        return parent::addRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', []);

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', [$serialized]);

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', []);

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', []);

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsernameCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsernameCanonical', []);

        return parent::getUsernameCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', []);

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailCanonical', []);

        return parent::getEmailCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', []);

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlainPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlainPassword', []);

        return parent::getPlainPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLogin', []);

        return parent::getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmationToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmationToken', []);

        return parent::getConfirmationToken();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', []);

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function hasRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRole', [$role]);

        return parent::hasRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonExpired', []);

        return parent::isAccountNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonLocked', []);

        return parent::isAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsNonExpired', []);

        return parent::isCredentialsNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsExpired', []);

        return parent::isCredentialsExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', []);

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function isExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExpired', []);

        return parent::isExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLocked', []);

        return parent::isLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isSuperAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSuperAdmin', []);

        return parent::isSuperAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', [$role]);

        return parent::removeRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', [$username]);

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsernameCanonical($usernameCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsernameCanonical', [$usernameCanonical]);

        return parent::setUsernameCanonical($usernameCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function setCredentialsExpireAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredentialsExpireAt', [$date]);

        return parent::setCredentialsExpireAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setCredentialsExpired($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredentialsExpired', [$boolean]);

        return parent::setCredentialsExpired($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', [$boolean]);

        return parent::setEnabled($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setExpired($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpired', [$boolean]);

        return parent::setExpired($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiresAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiresAt', [$date]);

        return parent::setExpiresAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', [$password]);

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setSuperAdmin($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuperAdmin', [$boolean]);

        return parent::setSuperAdmin($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setPlainPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlainPassword', [$password]);

        return parent::setPlainPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLogin(\DateTime $time = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLogin', [$time]);

        return parent::setLastLogin($time);
    }

    /**
     * {@inheritDoc}
     */
    public function setLocked($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocked', [$boolean]);

        return parent::setLocked($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmationToken($confirmationToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmationToken', [$confirmationToken]);

        return parent::setConfirmationToken($confirmationToken);
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordRequestedAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordRequestedAt', [$date]);

        return parent::setPasswordRequestedAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordRequestedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordRequestedAt', []);

        return parent::getPasswordRequestedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isPasswordRequestNonExpired($ttl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPasswordRequestNonExpired', [$ttl]);

        return parent::isPasswordRequestNonExpired($ttl);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', [$roles]);

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroups', []);

        return parent::getGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupNames', []);

        return parent::getGroupNames();
    }

    /**
     * {@inheritDoc}
     */
    public function hasGroup($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasGroup', [$name]);

        return parent::hasGroup($name);
    }

    /**
     * {@inheritDoc}
     */
    public function addGroup(\FOS\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGroup', [$group]);

        return parent::addGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGroup(\FOS\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGroup', [$group]);

        return parent::removeGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
