<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \AppBundle\Entity\Product implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Product' . "\0" . 'id', 'image', 'images', 'order_products', 'countries', 'contractors', 'prices', 'special', 'code_groups', 'connected_products_from', 'connected_products_to', 'page_type', 'page_category', 'category', 'type', 'creator', 'cities', 'months', 'enabled', 'single', 'confirmation', 'in_page', 'without_code', 'with_code', '' . "\0" . 'AppBundle\\Entity\\Product' . "\0" . 'model', '' . "\0" . 'AppBundle\\Entity\\Product' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\Product' . "\0" . 'updated', '' . "\0" . 'AppBundle\\Entity\\Product' . "\0" . 'deleted', 'translations', 'newTranslations', 'currentLocale', 'defaultLocale');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Product' . "\0" . 'id', 'image', 'images', 'order_products', 'countries', 'contractors', 'prices', 'special', 'code_groups', 'connected_products_from', 'connected_products_to', 'page_type', 'page_category', 'category', 'type', 'creator', 'cities', 'months', 'enabled', 'single', 'confirmation', 'in_page', 'without_code', 'with_code', '' . "\0" . 'AppBundle\\Entity\\Product' . "\0" . 'model', '' . "\0" . 'AppBundle\\Entity\\Product' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\Product' . "\0" . 'updated', '' . "\0" . 'AppBundle\\Entity\\Product' . "\0" . 'deleted', 'translations', 'newTranslations', 'currentLocale', 'defaultLocale');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Product $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __call($method, $args)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', array($method, $args));

        return parent::__call($method, $args);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatar', array());

        return parent::getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice($currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array($currency));

        return parent::getPrice($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceDiscount($currency, $discount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceDiscount', array($currency, $discount));

        return parent::getPriceDiscount($currency, $discount);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceDiscountAmount($currency, $discount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceDiscountAmount', array($currency, $discount));

        return parent::getPriceDiscountAmount($currency, $discount);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeName', array());

        return parent::getTypeName();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setModel($model)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModel', array($model));

        return parent::setModel($model);
    }

    /**
     * {@inheritDoc}
     */
    public function getModel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModel', array());

        return parent::getModel();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeight($weight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeight', array($weight));

        return parent::setWeight($weight);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeight', array());

        return parent::getWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', array($enabled));

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', array());

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', array($updated));

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', array());

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(\AppBundle\Entity\Image $image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage(\AppBundle\Entity\Image $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', array($image));

        return parent::addImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage(\AppBundle\Entity\Image $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', array($image));

        return parent::removeImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', array());

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function getImagesSort()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagesSort', array());

        return parent::getImagesSort();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(\AppBundle\Entity\ProductCategory $category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(\AppBundle\Entity\ProductType $type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator(\AppBundle\Entity\User $creator = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', array($creator));

        return parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', array());

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function addConnectedProductsFrom(\AppBundle\Entity\ProductConnection $connectedProductsFrom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addConnectedProductsFrom', array($connectedProductsFrom));

        return parent::addConnectedProductsFrom($connectedProductsFrom);
    }

    /**
     * {@inheritDoc}
     */
    public function removeConnectedProductsFrom(\AppBundle\Entity\ProductConnection $connectedProductsFrom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeConnectedProductsFrom', array($connectedProductsFrom));

        return parent::removeConnectedProductsFrom($connectedProductsFrom);
    }

    /**
     * {@inheritDoc}
     */
    public function getConnectedProductsFrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConnectedProductsFrom', array());

        return parent::getConnectedProductsFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function addConnectedProductsTo(\AppBundle\Entity\ProductConnection $connectedProductsTo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addConnectedProductsTo', array($connectedProductsTo));

        return parent::addConnectedProductsTo($connectedProductsTo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeConnectedProductsTo(\AppBundle\Entity\ProductConnection $connectedProductsTo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeConnectedProductsTo', array($connectedProductsTo));

        return parent::removeConnectedProductsTo($connectedProductsTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getConnectedProductsTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConnectedProductsTo', array());

        return parent::getConnectedProductsTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMonths($months)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMonths', array($months));

        return parent::setMonths($months);
    }

    /**
     * {@inheritDoc}
     */
    public function getMonths()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMonths', array());

        return parent::getMonths();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageType(\AppBundle\Entity\PageType $pageType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageType', array($pageType));

        return parent::setPageType($pageType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageType', array());

        return parent::getPageType();
    }

    /**
     * {@inheritDoc}
     */
    public function addPrice(\AppBundle\Entity\ProductPrice $price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPrice', array($price));

        return parent::addPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function removePrice(\AppBundle\Entity\ProductPrice $price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePrice', array($price));

        return parent::removePrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrices()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrices', array());

        return parent::getPrices();
    }

    /**
     * {@inheritDoc}
     */
    public function setInPage($inPage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInPage', array($inPage));

        return parent::setInPage($inPage);
    }

    /**
     * {@inheritDoc}
     */
    public function getInPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInPage', array());

        return parent::getInPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setWithoutCode($withoutCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWithoutCode', array($withoutCode));

        return parent::setWithoutCode($withoutCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getWithoutCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWithoutCode', array());

        return parent::getWithoutCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setWithCode($withCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWithCode', array($withCode));

        return parent::setWithCode($withCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getWithCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWithCode', array());

        return parent::getWithCode();
    }

    /**
     * {@inheritDoc}
     */
    public function addCountry(\AppBundle\Entity\Country $country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCountry', array($country));

        return parent::addCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCountry(\AppBundle\Entity\Country $country)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCountry', array($country));

        return parent::removeCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountries', array());

        return parent::getCountries();
    }

    /**
     * {@inheritDoc}
     */
    public function setCities($cities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCities', array($cities));

        return parent::setCities($cities);
    }

    /**
     * {@inheritDoc}
     */
    public function getCities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCities', array());

        return parent::getCities();
    }

    /**
     * {@inheritDoc}
     */
    public function addCodeGroup(\AppBundle\Entity\CodeGroup $codeGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCodeGroup', array($codeGroup));

        return parent::addCodeGroup($codeGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCodeGroup(\AppBundle\Entity\CodeGroup $codeGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCodeGroup', array($codeGroup));

        return parent::removeCodeGroup($codeGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeGroups', array());

        return parent::getCodeGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function setSingle($single)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSingle', array($single));

        return parent::setSingle($single);
    }

    /**
     * {@inheritDoc}
     */
    public function getSingle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSingle', array());

        return parent::getSingle();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmation($confirmation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmation', array($confirmation));

        return parent::setConfirmation($confirmation);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmation', array());

        return parent::getConfirmation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', array($deleted));

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', array());

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setSpecial($special)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSpecial', array($special));

        return parent::setSpecial($special);
    }

    /**
     * {@inheritDoc}
     */
    public function getSpecial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSpecial', array());

        return parent::getSpecial();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageCategory(\AppBundle\Entity\PageCategory $pageCategory = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageCategory', array($pageCategory));

        return parent::setPageCategory($pageCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageCategory', array());

        return parent::getPageCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function addContractor(\AppBundle\Entity\UserProduct $contractor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContractor', array($contractor));

        return parent::addContractor($contractor);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContractor(\AppBundle\Entity\UserProduct $contractor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContractor', array($contractor));

        return parent::removeContractor($contractor);
    }

    /**
     * {@inheritDoc}
     */
    public function getContractors()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContractors', array());

        return parent::getContractors();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderProduct(\AppBundle\Entity\OrderProduct $orderProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderProduct', array($orderProduct));

        return parent::addOrderProduct($orderProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrderProduct(\AppBundle\Entity\OrderProduct $orderProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrderProduct', array($orderProduct));

        return parent::removeOrderProduct($orderProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderProducts', array());

        return parent::getOrderProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function getTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTranslations', array());

        return parent::getTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function getNewTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewTranslations', array());

        return parent::getNewTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function addTranslation($translation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTranslation', array($translation));

        return parent::addTranslation($translation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTranslation($translation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTranslation', array($translation));

        return parent::removeTranslation($translation);
    }

    /**
     * {@inheritDoc}
     */
    public function translate($locale = NULL, $fallbackToDefault = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'translate', array($locale, $fallbackToDefault));

        return parent::translate($locale, $fallbackToDefault);
    }

    /**
     * {@inheritDoc}
     */
    public function mergeNewTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'mergeNewTranslations', array());

        return parent::mergeNewTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentLocale', array($locale));

        return parent::setCurrentLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentLocale', array());

        return parent::getCurrentLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultLocale', array($locale));

        return parent::setDefaultLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultLocale', array());

        return parent::getDefaultLocale();
    }

}
