<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrderProduct extends \AppBundle\Entity\OrderProduct implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\OrderProduct' . "\0" . 'id', 'product', 'code', 'code_side', 'codes', 'page', 'order', 'image', 'images', 'contractor', 'creator', 'confirmation', 'rating', 'review', 'customer_confirmed', 'contractor_confirmed', '' . "\0" . 'AppBundle\\Entity\\OrderProduct' . "\0" . 'name', 'discount', 'provision', 'discount_price', 'provision_price', 'price', '' . "\0" . 'AppBundle\\Entity\\OrderProduct' . "\0" . 'currency', 'amount', '' . "\0" . 'AppBundle\\Entity\\OrderProduct' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\OrderProduct' . "\0" . 'updated');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\OrderProduct' . "\0" . 'id', 'product', 'code', 'code_side', 'codes', 'page', 'order', 'image', 'images', 'contractor', 'creator', 'confirmation', 'rating', 'review', 'customer_confirmed', 'contractor_confirmed', '' . "\0" . 'AppBundle\\Entity\\OrderProduct' . "\0" . 'name', 'discount', 'provision', 'discount_price', 'provision_price', 'price', '' . "\0" . 'AppBundle\\Entity\\OrderProduct' . "\0" . 'currency', 'amount', '' . "\0" . 'AppBundle\\Entity\\OrderProduct' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\OrderProduct' . "\0" . 'updated');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OrderProduct $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPartnerStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartnerStock', array());

        return parent::getPartnerStock();
    }

    /**
     * {@inheritDoc}
     */
    public function getAllStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAllStock', array());

        return parent::getAllStock();
    }

    /**
     * {@inheritDoc}
     */
    public function getStock()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStock', array());

        return parent::getStock();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct(\AppBundle\Entity\Product $product = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct', array($product));

        return parent::setProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct', array());

        return parent::getProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrder(\AppBundle\Entity\Order $order = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrder', array($order));

        return parent::setOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrder', array());

        return parent::getOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator(\AppBundle\Entity\User $creator = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', array($creator));

        return parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', array());

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setTax($tax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTax', array($tax));

        return parent::setTax($tax);
    }

    /**
     * {@inheritDoc}
     */
    public function getTax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTax', array());

        return parent::getTax();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmount($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmount', array($amount));

        return parent::setAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount', array());

        return parent::getAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', array($updated));

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', array());

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceBuy($priceBuy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceBuy', array($priceBuy));

        return parent::setPriceBuy($priceBuy);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceBuy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceBuy', array());

        return parent::getPriceBuy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency($currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', array($currency));

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', array());

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setPage(\AppBundle\Entity\Page $page = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPage', array($page));

        return parent::setPage($page);
    }

    /**
     * {@inheritDoc}
     */
    public function getPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPage', array());

        return parent::getPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setContractor(\AppBundle\Entity\User $contractor = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContractor', array($contractor));

        return parent::setContractor($contractor);
    }

    /**
     * {@inheritDoc}
     */
    public function getContractor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContractor', array());

        return parent::getContractor();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmation($confirmation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmation', array($confirmation));

        return parent::setConfirmation($confirmation);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmation', array());

        return parent::getConfirmation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerConfirmed($customerConfirmed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerConfirmed', array($customerConfirmed));

        return parent::setCustomerConfirmed($customerConfirmed);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerConfirmed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerConfirmed', array());

        return parent::getCustomerConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    public function setContractorConfirmed($contractorConfirmed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContractorConfirmed', array($contractorConfirmed));

        return parent::setContractorConfirmed($contractorConfirmed);
    }

    /**
     * {@inheritDoc}
     */
    public function getContractorConfirmed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContractorConfirmed', array());

        return parent::getContractorConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    public function addImage(\AppBundle\Entity\Image $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImage', array($image));

        return parent::addImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImage(\AppBundle\Entity\Image $image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImage', array($image));

        return parent::removeImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImages', array());

        return parent::getImages();
    }

    /**
     * {@inheritDoc}
     */
    public function getImagesSort()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImagesSort', array());

        return parent::getImagesSort();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(\AppBundle\Entity\Code $code = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', array($code));

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', array());

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function addCode(\AppBundle\Entity\Code $code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCode', array($code));

        return parent::addCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCode(\AppBundle\Entity\Code $code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCode', array($code));

        return parent::removeCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodes', array());

        return parent::getCodes();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(\AppBundle\Entity\Image $image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setRating($rating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating', array($rating));

        return parent::setRating($rating);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating', array());

        return parent::getRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setRewiev($rewiev)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRewiev', array($rewiev));

        return parent::setRewiev($rewiev);
    }

    /**
     * {@inheritDoc}
     */
    public function getRewiev()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRewiev', array());

        return parent::getRewiev();
    }

    /**
     * {@inheritDoc}
     */
    public function setReview($review)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReview', array($review));

        return parent::setReview($review);
    }

    /**
     * {@inheritDoc}
     */
    public function getReview()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReview', array());

        return parent::getReview();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodeSide(\AppBundle\Entity\Code $codeSide = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodeSide', array($codeSide));

        return parent::setCodeSide($codeSide);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodeSide()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodeSide', array());

        return parent::getCodeSide();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscount($discount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscount', array($discount));

        return parent::setDiscount($discount);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscount', array());

        return parent::getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvision($provision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvision', array($provision));

        return parent::setProvision($provision);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvision', array());

        return parent::getProvision();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountPrice($discountPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountPrice', array($discountPrice));

        return parent::setDiscountPrice($discountPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountPrice', array());

        return parent::getDiscountPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvisionPrice($provisionPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvisionPrice', array($provisionPrice));

        return parent::setProvisionPrice($provisionPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvisionPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvisionPrice', array());

        return parent::getProvisionPrice();
    }

}
