<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Order extends \AppBundle\Entity\Order implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'id', 'order_products', 'status_history', 'payments', 'cart_owners', 'status', 'buyer', 'parent_partner', 'partner', 'creator', 'note', 'delivery', 'billing', 'billing_address', 'delivery_address', 'invoice_id', 'contractor_id', 'invoice_type', 'invoice_number', 'paid', 'confirmed', 'done', 'canceled', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'deleted', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'updated', 'discount', 'provision', 'discount_price', 'provision_price', 'price', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'currency', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'locale', 'products_count', 'items_count', 'invoice');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'id', 'order_products', 'status_history', 'payments', 'cart_owners', 'status', 'buyer', 'parent_partner', 'partner', 'creator', 'note', 'delivery', 'billing', 'billing_address', 'delivery_address', 'invoice_id', 'contractor_id', 'invoice_type', 'invoice_number', 'paid', 'confirmed', 'done', 'canceled', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'deleted', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'updated', 'discount', 'provision', 'discount_price', 'provision_price', 'price', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'currency', '' . "\0" . 'AppBundle\\Entity\\Order' . "\0" . 'locale', 'products_count', 'items_count', 'invoice');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Order $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function onlinePayment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'onlinePayment', array());

        return parent::onlinePayment();
    }

    /**
     * {@inheritDoc}
     */
    public function setNote($note)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNote', array($note));

        return parent::setNote($note);
    }

    /**
     * {@inheritDoc}
     */
    public function getNote()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNote', array());

        return parent::getNote();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator(\AppBundle\Entity\User $creator = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', array($creator));

        return parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', array());

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(\AppBundle\Entity\OrderStatus $status = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentStatus', array());

        return parent::getCurrentStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduct(\AppBundle\Entity\OrderProduct $products)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduct', array($products));

        return parent::addProduct($products);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduct(\AppBundle\Entity\OrderProduct $products)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduct', array($products));

        return parent::removeProduct($products);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducts', array());

        return parent::getProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderProduct(\AppBundle\Entity\OrderProduct $orderProducts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderProduct', array($orderProducts));

        return parent::addOrderProduct($orderProducts);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrderProduct(\AppBundle\Entity\OrderProduct $orderProducts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrderProduct', array($orderProducts));

        return parent::removeOrderProduct($orderProducts);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderProducts', array());

        return parent::getOrderProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', array($updated));

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', array());

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setSent($sent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSent', array($sent));

        return parent::setSent($sent);
    }

    /**
     * {@inheritDoc}
     */
    public function getSent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSent', array());

        return parent::getSent();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelivered($delivered)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelivered', array($delivered));

        return parent::setDelivered($delivered);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelivered()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelivered', array());

        return parent::getDelivered();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmed($confirmed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmed', array($confirmed));

        return parent::setConfirmed($confirmed);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmed', array());

        return parent::getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', array($deleted));

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', array());

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function addStatusHistory(\AppBundle\Entity\OrderStatusHistory $statusHistory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStatusHistory', array($statusHistory));

        return parent::addStatusHistory($statusHistory);
    }

    /**
     * {@inheritDoc}
     */
    public function removeStatusHistory(\AppBundle\Entity\OrderStatusHistory $statusHistory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeStatusHistory', array($statusHistory));

        return parent::removeStatusHistory($statusHistory);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusHistory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusHistory', array());

        return parent::getStatusHistory();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setProductsCount($productsCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProductsCount', array($productsCount));

        return parent::setProductsCount($productsCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductsCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductsCount', array());

        return parent::getProductsCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemsCount($itemsCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemsCount', array($itemsCount));

        return parent::setItemsCount($itemsCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemsCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemsCount', array());

        return parent::getItemsCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setCanceled($canceled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCanceled', array($canceled));

        return parent::setCanceled($canceled);
    }

    /**
     * {@inheritDoc}
     */
    public function getCanceled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCanceled', array());

        return parent::getCanceled();
    }

    /**
     * {@inheritDoc}
     */
    public function setDone($done)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDone', array($done));

        return parent::setDone($done);
    }

    /**
     * {@inheritDoc}
     */
    public function getDone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDone', array());

        return parent::getDone();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaid($paid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaid', array($paid));

        return parent::setPaid($paid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaid', array());

        return parent::getPaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setManager(\AppBundle\Entity\User $manager = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManager', array($manager));

        return parent::setManager($manager);
    }

    /**
     * {@inheritDoc}
     */
    public function getManager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManager', array());

        return parent::getManager();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriceWork($priceWork)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriceWork', array($priceWork));

        return parent::setPriceWork($priceWork);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriceWork()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriceWork', array());

        return parent::getPriceWork();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuyer(\AppBundle\Entity\User $buyer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuyer', array($buyer));

        return parent::setBuyer($buyer);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuyer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuyer', array());

        return parent::getBuyer();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency($currency)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', array($currency));

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', array());

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocale', array($locale));

        return parent::setLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocale', array());

        return parent::getLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function addPayment(\AppBundle\Entity\Payment $payment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPayment', array($payment));

        return parent::addPayment($payment);
    }

    /**
     * {@inheritDoc}
     */
    public function removePayment(\AppBundle\Entity\Payment $payment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePayment', array($payment));

        return parent::removePayment($payment);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayments', array());

        return parent::getPayments();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelivery($delivery)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelivery', array($delivery));

        return parent::setDelivery($delivery);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelivery()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelivery', array());

        return parent::getDelivery();
    }

    /**
     * {@inheritDoc}
     */
    public function setBilling($billing)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBilling', array($billing));

        return parent::setBilling($billing);
    }

    /**
     * {@inheritDoc}
     */
    public function getBilling()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBilling', array());

        return parent::getBilling();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoice($invoice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoice', array($invoice));

        return parent::setInvoice($invoice);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoice', array());

        return parent::getInvoice();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoiceId($invoiceId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoiceId', array($invoiceId));

        return parent::setInvoiceId($invoiceId);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceId', array());

        return parent::getInvoiceId();
    }

    /**
     * {@inheritDoc}
     */
    public function setContractorId($contractorId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContractorId', array($contractorId));

        return parent::setContractorId($contractorId);
    }

    /**
     * {@inheritDoc}
     */
    public function getContractorId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContractorId', array());

        return parent::getContractorId();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoiceType($invoiceType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoiceType', array($invoiceType));

        return parent::setInvoiceType($invoiceType);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceType', array());

        return parent::getInvoiceType();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddress(\AppBundle\Entity\Address $billingAddress = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddress', array($billingAddress));

        return parent::setBillingAddress($billingAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress', array());

        return parent::getBillingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryAddress(\AppBundle\Entity\Address $deliveryAddress = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryAddress', array($deliveryAddress));

        return parent::setDeliveryAddress($deliveryAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryAddress', array());

        return parent::getDeliveryAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoiceNumber($invoiceNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoiceNumber', array($invoiceNumber));

        return parent::setInvoiceNumber($invoiceNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceNumber', array());

        return parent::getInvoiceNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function addCartOwner(\AppBundle\Entity\User $cartOwner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCartOwner', array($cartOwner));

        return parent::addCartOwner($cartOwner);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCartOwner(\AppBundle\Entity\User $cartOwner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCartOwner', array($cartOwner));

        return parent::removeCartOwner($cartOwner);
    }

    /**
     * {@inheritDoc}
     */
    public function getCartOwners()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCartOwners', array());

        return parent::getCartOwners();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscount($discount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscount', array($discount));

        return parent::setDiscount($discount);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscount', array());

        return parent::getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvision($provision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvision', array($provision));

        return parent::setProvision($provision);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvision', array());

        return parent::getProvision();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountPrice($discountPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountPrice', array($discountPrice));

        return parent::setDiscountPrice($discountPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountPrice', array());

        return parent::getDiscountPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvisionPrice($provisionPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvisionPrice', array($provisionPrice));

        return parent::setProvisionPrice($provisionPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvisionPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvisionPrice', array());

        return parent::getProvisionPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentPartner(\AppBundle\Entity\User $parentPartner = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentPartner', array($parentPartner));

        return parent::setParentPartner($parentPartner);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentPartner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentPartner', array());

        return parent::getParentPartner();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartner(\AppBundle\Entity\User $partner = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartner', array($partner));

        return parent::setPartner($partner);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartner', array());

        return parent::getPartner();
    }

}
