<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrderStatus extends \AppBundle\Entity\OrderStatus implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\OrderStatus' . "\0" . 'id', 'orders', 'status_history', 'creator', 'send_mail', 'send_sms', 'contractor_confirmation', 'customer_confirmation', 'payment_manual', 'payment_success', 'payment_fail', 'confirmed', 'done', 'canceled', 'first', '' . "\0" . 'AppBundle\\Entity\\OrderStatus' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\OrderStatus' . "\0" . 'updated', '' . "\0" . 'AppBundle\\Entity\\OrderStatus' . "\0" . 'deleted', 'translations', 'newTranslations', 'currentLocale', 'defaultLocale');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\OrderStatus' . "\0" . 'id', 'orders', 'status_history', 'creator', 'send_mail', 'send_sms', 'contractor_confirmation', 'customer_confirmation', 'payment_manual', 'payment_success', 'payment_fail', 'confirmed', 'done', 'canceled', 'first', '' . "\0" . 'AppBundle\\Entity\\OrderStatus' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\OrderStatus' . "\0" . 'updated', '' . "\0" . 'AppBundle\\Entity\\OrderStatus' . "\0" . 'deleted', 'translations', 'newTranslations', 'currentLocale', 'defaultLocale');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OrderStatus $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __call($method, $args)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__call', array($method, $args));

        return parent::__call($method, $args);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrder(\AppBundle\Entity\Order $orders)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrder', array($orders));

        return parent::addOrder($orders);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrder(\AppBundle\Entity\Order $orders)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrder', array($orders));

        return parent::removeOrder($orders);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrders', array());

        return parent::getOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator(\AppBundle\Entity\User $creator = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', array($creator));

        return parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', array());

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', array($updated));

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', array());

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaid($paid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaid', array($paid));

        return parent::setPaid($paid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaid', array());

        return parent::getPaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setSent($sent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSent', array($sent));

        return parent::setSent($sent);
    }

    /**
     * {@inheritDoc}
     */
    public function getSent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSent', array());

        return parent::getSent();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelivered($delivered)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelivered', array($delivered));

        return parent::setDelivered($delivered);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelivered()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelivered', array());

        return parent::getDelivered();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmed($confirmed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmed', array($confirmed));

        return parent::setConfirmed($confirmed);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmed', array());

        return parent::getConfirmed();
    }

    /**
     * {@inheritDoc}
     */
    public function setDone($done)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDone', array($done));

        return parent::setDone($done);
    }

    /**
     * {@inheritDoc}
     */
    public function getDone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDone', array());

        return parent::getDone();
    }

    /**
     * {@inheritDoc}
     */
    public function addStatusHistory(\AppBundle\Entity\OrderStatusHistory $statusHistory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addStatusHistory', array($statusHistory));

        return parent::addStatusHistory($statusHistory);
    }

    /**
     * {@inheritDoc}
     */
    public function removeStatusHistory(\AppBundle\Entity\OrderStatusHistory $statusHistory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeStatusHistory', array($statusHistory));

        return parent::removeStatusHistory($statusHistory);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusHistory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusHistory', array());

        return parent::getStatusHistory();
    }

    /**
     * {@inheritDoc}
     */
    public function setSendMail($sendMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSendMail', array($sendMail));

        return parent::setSendMail($sendMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getSendMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendMail', array());

        return parent::getSendMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setCanceled($canceled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCanceled', array($canceled));

        return parent::setCanceled($canceled);
    }

    /**
     * {@inheritDoc}
     */
    public function getCanceled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCanceled', array());

        return parent::getCanceled();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirst($first)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirst', array($first));

        return parent::setFirst($first);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirst()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirst', array());

        return parent::getFirst();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', array($deleted));

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', array());

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setContractorConfirmation($contractorConfirmation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContractorConfirmation', array($contractorConfirmation));

        return parent::setContractorConfirmation($contractorConfirmation);
    }

    /**
     * {@inheritDoc}
     */
    public function getContractorConfirmation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContractorConfirmation', array());

        return parent::getContractorConfirmation();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerConfirmation($customerConfirmation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerConfirmation', array($customerConfirmation));

        return parent::setCustomerConfirmation($customerConfirmation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerConfirmation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerConfirmation', array());

        return parent::getCustomerConfirmation();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentManual($paymentManual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentManual', array($paymentManual));

        return parent::setPaymentManual($paymentManual);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentManual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentManual', array());

        return parent::getPaymentManual();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentSuccess($paymentSuccess)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentSuccess', array($paymentSuccess));

        return parent::setPaymentSuccess($paymentSuccess);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentSuccess()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentSuccess', array());

        return parent::getPaymentSuccess();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentFail($paymentFail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentFail', array($paymentFail));

        return parent::setPaymentFail($paymentFail);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentFail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentFail', array());

        return parent::getPaymentFail();
    }

    /**
     * {@inheritDoc}
     */
    public function setSendSms($sendSms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSendSms', array($sendSms));

        return parent::setSendSms($sendSms);
    }

    /**
     * {@inheritDoc}
     */
    public function getSendSms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSendSms', array());

        return parent::getSendSms();
    }

    /**
     * {@inheritDoc}
     */
    public function getTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTranslations', array());

        return parent::getTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function getNewTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNewTranslations', array());

        return parent::getNewTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function addTranslation($translation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTranslation', array($translation));

        return parent::addTranslation($translation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTranslation($translation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTranslation', array($translation));

        return parent::removeTranslation($translation);
    }

    /**
     * {@inheritDoc}
     */
    public function translate($locale = NULL, $fallbackToDefault = true)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'translate', array($locale, $fallbackToDefault));

        return parent::translate($locale, $fallbackToDefault);
    }

    /**
     * {@inheritDoc}
     */
    public function mergeNewTranslations()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'mergeNewTranslations', array());

        return parent::mergeNewTranslations();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrentLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrentLocale', array($locale));

        return parent::setCurrentLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrentLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrentLocale', array());

        return parent::getCurrentLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function setDefaultLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDefaultLocale', array($locale));

        return parent::setDefaultLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultLocale', array());

        return parent::getDefaultLocale();
    }

}
