<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Address extends \AppBundle\Entity\Address implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Address' . "\0" . 'id', 'billing_orders', 'delivery_orders', 'billing_users', 'delivery_users', 'cemeteries', 'pages', 'creator', '' . "\0" . 'AppBundle\\Entity\\Address' . "\0" . 'company', 'tax_id', 'tax_id_name', 'regon', 'krs', 'first_name', 'last_name', 'address', 'city', 'postal_code', 'country', '' . "\0" . 'AppBundle\\Entity\\Address' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\Address' . "\0" . 'updated', '' . "\0" . 'AppBundle\\Entity\\Address' . "\0" . 'deleted');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Address' . "\0" . 'id', 'billing_orders', 'delivery_orders', 'billing_users', 'delivery_users', 'cemeteries', 'pages', 'creator', '' . "\0" . 'AppBundle\\Entity\\Address' . "\0" . 'company', 'tax_id', 'tax_id_name', 'regon', 'krs', 'first_name', 'last_name', 'address', 'city', 'postal_code', 'country', '' . "\0" . 'AppBundle\\Entity\\Address' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\Address' . "\0" . 'updated', '' . "\0" . 'AppBundle\\Entity\\Address' . "\0" . 'deleted');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Address $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getInvoiceTypes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceTypes', array());

        return parent::getInvoiceTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceType', array($type));

        return parent::getInvoiceType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function toString($parameters = array (
))
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toString', array($parameters));

        return parent::toString($parameters);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxId($taxId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxId', array($taxId));

        return parent::setTaxId($taxId);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxId', array());

        return parent::getTaxId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostalCode($postalCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostalCode', array($postalCode));

        return parent::setPostalCode($postalCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostalCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostalCode', array());

        return parent::getPostalCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', array($updated));

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', array());

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function addBillingUser(\AppBundle\Entity\User $billingUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBillingUser', array($billingUser));

        return parent::addBillingUser($billingUser);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBillingUser(\AppBundle\Entity\User $billingUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBillingUser', array($billingUser));

        return parent::removeBillingUser($billingUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingUsers', array());

        return parent::getBillingUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function addDeliveryUser(\AppBundle\Entity\User $deliveryUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDeliveryUser', array($deliveryUser));

        return parent::addDeliveryUser($deliveryUser);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDeliveryUser(\AppBundle\Entity\User $deliveryUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDeliveryUser', array($deliveryUser));

        return parent::removeDeliveryUser($deliveryUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryUsers', array());

        return parent::getDeliveryUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator(\AppBundle\Entity\User $creator = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', array($creator));

        return parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', array());

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(\AppBundle\Entity\Country $country = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCompany($company)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCompany', array($company));

        return parent::setCompany($company);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompany()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompany', array());

        return parent::getCompany();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', array($firstName));

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', array());

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', array($lastName));

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', array());

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function setTaxIdName($taxIdName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTaxIdName', array($taxIdName));

        return parent::setTaxIdName($taxIdName);
    }

    /**
     * {@inheritDoc}
     */
    public function getTaxIdName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTaxIdName', array());

        return parent::getTaxIdName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', array($deleted));

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', array());

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegon($regon)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegon', array($regon));

        return parent::setRegon($regon);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegon()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegon', array());

        return parent::getRegon();
    }

    /**
     * {@inheritDoc}
     */
    public function setKrs($krs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKrs', array($krs));

        return parent::setKrs($krs);
    }

    /**
     * {@inheritDoc}
     */
    public function getKrs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKrs', array());

        return parent::getKrs();
    }

    /**
     * {@inheritDoc}
     */
    public function addBillingOrder(\AppBundle\Entity\Order $billingOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBillingOrder', array($billingOrder));

        return parent::addBillingOrder($billingOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBillingOrder(\AppBundle\Entity\Order $billingOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBillingOrder', array($billingOrder));

        return parent::removeBillingOrder($billingOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingOrders', array());

        return parent::getBillingOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function addDeliveryOrder(\AppBundle\Entity\Order $deliveryOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDeliveryOrder', array($deliveryOrder));

        return parent::addDeliveryOrder($deliveryOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDeliveryOrder(\AppBundle\Entity\Order $deliveryOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDeliveryOrder', array($deliveryOrder));

        return parent::removeDeliveryOrder($deliveryOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryOrders', array());

        return parent::getDeliveryOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function addCemetery(\AppBundle\Entity\Cemetery $cemetery)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCemetery', array($cemetery));

        return parent::addCemetery($cemetery);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCemetery(\AppBundle\Entity\Cemetery $cemetery)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCemetery', array($cemetery));

        return parent::removeCemetery($cemetery);
    }

    /**
     * {@inheritDoc}
     */
    public function getCemeteries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCemeteries', array());

        return parent::getCemeteries();
    }

    /**
     * {@inheritDoc}
     */
    public function addPage(\AppBundle\Entity\Page $page)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPage', array($page));

        return parent::addPage($page);
    }

    /**
     * {@inheritDoc}
     */
    public function removePage(\AppBundle\Entity\Page $page)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePage', array($page));

        return parent::removePage($page);
    }

    /**
     * {@inheritDoc}
     */
    public function getPages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPages', array());

        return parent::getPages();
    }

}
