<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \AppBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'cemeteries', 'products', 'created_user_products', 'created_code_groups', 'created_credentials', 'created_order_products', 'created_page_categories', 'created_page_types', 'created_product_categories', 'created_product_connections', 'created_product_types', 'created_payments', 'created_status_histories', 'created_messages', 'recived_messages', 'updated_messages', 'created_groups', 'created_posts', 'created_mails', 'created_products', 'created_order_statuses', 'pages', 'created_pages', 'credentials', 'cart', 'orders', 'created_orders', 'parent_partner_orders', 'partner_orders', 'created_addresses', 'contracted_orders', 'families', 'first_name', 'last_name', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'phone', 'billing_address', 'delivery_address', 'type', 'registration_token', 'notification_order', 'invoice', 'ads', 'ads_show', 'ads_name', 'ads_description', 'ad_mobile', 'ad_desktop', 'ad_link', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'locale', 'file', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'path', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'description', 'discount', 'provision', 'rating', 'cities', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'facebook_id', 'notification_message', 'notification_post', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'updated', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'deleted', 'created_users', 'creator', 'partners', 'parent_partner', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'parent_partner_code', 'username', 'usernameCanonical', 'email', 'emailCanonical', 'enabled', 'salt', 'password', 'plainPassword', 'lastLogin', 'confirmationToken', 'passwordRequestedAt', 'groups', 'locked', 'expired', 'expiresAt', 'roles', 'credentialsExpired', 'credentialsExpireAt');
        }

        return array('__isInitialized__', 'id', 'cemeteries', 'products', 'created_user_products', 'created_code_groups', 'created_credentials', 'created_order_products', 'created_page_categories', 'created_page_types', 'created_product_categories', 'created_product_connections', 'created_product_types', 'created_payments', 'created_status_histories', 'created_messages', 'recived_messages', 'updated_messages', 'created_groups', 'created_posts', 'created_mails', 'created_products', 'created_order_statuses', 'pages', 'created_pages', 'credentials', 'cart', 'orders', 'created_orders', 'parent_partner_orders', 'partner_orders', 'created_addresses', 'contracted_orders', 'families', 'first_name', 'last_name', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'phone', 'billing_address', 'delivery_address', 'type', 'registration_token', 'notification_order', 'invoice', 'ads', 'ads_show', 'ads_name', 'ads_description', 'ad_mobile', 'ad_desktop', 'ad_link', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'locale', 'file', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'path', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'description', 'discount', 'provision', 'rating', 'cities', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'facebook_id', 'notification_message', 'notification_post', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'updated', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'deleted', 'created_users', 'creator', 'partners', 'parent_partner', '' . "\0" . 'AppBundle\\Entity\\User' . "\0" . 'parent_partner_code', 'username', 'usernameCanonical', 'email', 'emailCanonical', 'enabled', 'salt', 'password', 'plainPassword', 'lastLogin', 'confirmationToken', 'passwordRequestedAt', 'groups', 'locked', 'expired', 'expiresAt', 'roles', 'credentialsExpired', 'credentialsExpireAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailCanonical($emailCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailCanonical', array($emailCanonical));

        return parent::setEmailCanonical($emailCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function havePagePermission($page, $type = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'havePagePermission', array($page, $type));

        return parent::havePagePermission($page, $type);
    }

    /**
     * {@inheritDoc}
     */
    public function haveFamilyPermission($family, $type = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'haveFamilyPermission', array($family, $type));

        return parent::haveFamilyPermission($family, $type);
    }

    /**
     * {@inheritDoc}
     */
    public function getPermissionTypes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermissionTypes', array());

        return parent::getPermissionTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function getPermissionType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPermissionType', array($type));

        return parent::getPermissionType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceTypes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceTypes', array());

        return parent::getInvoiceTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceType', array($type));

        return parent::getInvoiceType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoicePrefixes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoicePrefixes', array());

        return parent::getInvoicePrefixes();
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoicePrefix($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoicePrefix', array($type));

        return parent::getInvoicePrefix($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceTaxes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceTaxes', array());

        return parent::getInvoiceTaxes();
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceTax($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceTax', array($type));

        return parent::getInvoiceTax($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoiceTaxRates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoiceTaxRates', array());

        return parent::getInvoiceTaxRates();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeName', array());

        return parent::getTypeName();
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeNames', array());

        return parent::getTypeNames();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', array($description));

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', array());

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setPath($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPath', array($path));

        return parent::setPath($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPath', array());

        return parent::getPath();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvatar($path)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvatar', array($path));

        return parent::setAvatar($path);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvatar()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvatar', array());

        return parent::getAvatar();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile(\Symfony\Component\HttpFoundation\File\UploadedFile $file = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', array($file));

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', array());

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpload', array());

        return parent::preUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function storeFilenameForRemove()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'storeFilenameForRemove', array());

        return parent::storeFilenameForRemove();
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpload', array());

        return parent::removeUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', array());

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', array());

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function getUploadRootDir()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUploadRootDir', array());

        return parent::getUploadRootDir();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', array($updated));

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', array());

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstName($firstName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstName', array($firstName));

        return parent::setFirstName($firstName);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstName', array());

        return parent::getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastName($lastName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastName', array($lastName));

        return parent::setLastName($lastName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastName', array());

        return parent::getLastName();
    }

    /**
     * {@inheritDoc}
     */
    public function getFullName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullName', array());

        return parent::getFullName();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotificationStockAlert($notificationStockAlert)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotificationStockAlert', array($notificationStockAlert));

        return parent::setNotificationStockAlert($notificationStockAlert);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotificationStockAlert()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotificationStockAlert', array());

        return parent::getNotificationStockAlert();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotificationOrder($notificationOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotificationOrder', array($notificationOrder));

        return parent::setNotificationOrder($notificationOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotificationOrder()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotificationOrder', array());

        return parent::getNotificationOrder();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartnerContact($partnerContact)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartnerContact', array($partnerContact));

        return parent::setPartnerContact($partnerContact);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartnerContact()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartnerContact', array());

        return parent::getPartnerContact();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegistrationToken($registrationToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegistrationToken', array($registrationToken));

        return parent::setRegistrationToken($registrationToken);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegistrationToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegistrationToken', array());

        return parent::getRegistrationToken();
    }

    /**
     * {@inheritDoc}
     */
    public function setBillingAddress(\AppBundle\Entity\Address $billingAddress = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBillingAddress', array($billingAddress));

        return parent::setBillingAddress($billingAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getBillingAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBillingAddress', array());

        return parent::getBillingAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeliveryAddress(\AppBundle\Entity\Address $deliveryAddress = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeliveryAddress', array($deliveryAddress));

        return parent::setDeliveryAddress($deliveryAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeliveryAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeliveryAddress', array());

        return parent::getDeliveryAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocale($locale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocale', array($locale));

        return parent::setLocale($locale);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocale', array());

        return parent::getLocale();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(\AppBundle\Entity\Country $country = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', array($country));

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', array());

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvoice($invoice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvoice', array($invoice));

        return parent::setInvoice($invoice);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvoice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvoice', array());

        return parent::getInvoice();
    }

    /**
     * {@inheritDoc}
     */
    public function addCemetery(\AppBundle\Entity\Cemetery $cemetery)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCemetery', array($cemetery));

        return parent::addCemetery($cemetery);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCemetery(\AppBundle\Entity\Cemetery $cemetery)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCemetery', array($cemetery));

        return parent::removeCemetery($cemetery);
    }

    /**
     * {@inheritDoc}
     */
    public function getCemeteries()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCemeteries', array());

        return parent::getCemeteries();
    }

    /**
     * {@inheritDoc}
     */
    public function addFamily(\AppBundle\Entity\Family $family)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFamily', array($family));

        return parent::addFamily($family);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFamily(\AppBundle\Entity\Family $family)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFamily', array($family));

        return parent::removeFamily($family);
    }

    /**
     * {@inheritDoc}
     */
    public function getFamilies()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFamilies', array());

        return parent::getFamilies();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebookId($facebookId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebookId', array($facebookId));

        return parent::setFacebookId($facebookId);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebookId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebookId', array());

        return parent::getFacebookId();
    }

    /**
     * {@inheritDoc}
     */
    public function addContractedOrder(\AppBundle\Entity\OrderProduct $contractedOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContractedOrder', array($contractedOrder));

        return parent::addContractedOrder($contractedOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContractedOrder(\AppBundle\Entity\OrderProduct $contractedOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContractedOrder', array($contractedOrder));

        return parent::removeContractedOrder($contractedOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getContractedOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContractedOrders', array());

        return parent::getContractedOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function addPage(\AppBundle\Entity\Page $page)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPage', array($page));

        return parent::addPage($page);
    }

    /**
     * {@inheritDoc}
     */
    public function removePage(\AppBundle\Entity\Page $page)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePage', array($page));

        return parent::removePage($page);
    }

    /**
     * {@inheritDoc}
     */
    public function getPages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPages', array());

        return parent::getPages();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrder(\AppBundle\Entity\Order $order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrder', array($order));

        return parent::addOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrder(\AppBundle\Entity\Order $order)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrder', array($order));

        return parent::removeOrder($order);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrders', array());

        return parent::getOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeleted($deleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeleted', array($deleted));

        return parent::setDeleted($deleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeleted', array());

        return parent::getDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator(\AppBundle\Entity\User $creator = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', array($creator));

        return parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', array());

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotificationMessage($notificationMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotificationMessage', array($notificationMessage));

        return parent::setNotificationMessage($notificationMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotificationMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotificationMessage', array());

        return parent::getNotificationMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotificationPost($notificationPost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotificationPost', array($notificationPost));

        return parent::setNotificationPost($notificationPost);
    }

    /**
     * {@inheritDoc}
     */
    public function getNotificationPost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotificationPost', array());

        return parent::getNotificationPost();
    }

    /**
     * {@inheritDoc}
     */
    public function setCart(\AppBundle\Entity\Order $cart = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCart', array($cart));

        return parent::setCart($cart);
    }

    /**
     * {@inheritDoc}
     */
    public function getCart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCart', array());

        return parent::getCart();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setRating($rating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating', array($rating));

        return parent::setRating($rating);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating', array());

        return parent::getRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setCities($cities)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCities', array($cities));

        return parent::setCities($cities);
    }

    /**
     * {@inheritDoc}
     */
    public function getCities()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCities', array());

        return parent::getCities();
    }

    /**
     * {@inheritDoc}
     */
    public function addCredential(\AppBundle\Entity\PageCredentials $credential)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCredential', array($credential));

        return parent::addCredential($credential);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCredential(\AppBundle\Entity\PageCredentials $credential)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCredential', array($credential));

        return parent::removeCredential($credential);
    }

    /**
     * {@inheritDoc}
     */
    public function getCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCredentials', array());

        return parent::getCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscount($discount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscount', array($discount));

        return parent::setDiscount($discount);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscount', array());

        return parent::getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduct(\AppBundle\Entity\UserProduct $product)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduct', array($product));

        return parent::addProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduct(\AppBundle\Entity\UserProduct $product)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduct', array($product));

        return parent::removeProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducts', array());

        return parent::getProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedUserProduct(\AppBundle\Entity\UserProduct $createdUserProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedUserProduct', array($createdUserProduct));

        return parent::addCreatedUserProduct($createdUserProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedUserProduct(\AppBundle\Entity\UserProduct $createdUserProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedUserProduct', array($createdUserProduct));

        return parent::removeCreatedUserProduct($createdUserProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedUserProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedUserProducts', array());

        return parent::getCreatedUserProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedCodeGroup(\AppBundle\Entity\CodeGroup $createdCodeGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedCodeGroup', array($createdCodeGroup));

        return parent::addCreatedCodeGroup($createdCodeGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedCodeGroup(\AppBundle\Entity\CodeGroup $createdCodeGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedCodeGroup', array($createdCodeGroup));

        return parent::removeCreatedCodeGroup($createdCodeGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedCodeGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedCodeGroups', array());

        return parent::getCreatedCodeGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedCredential(\AppBundle\Entity\PageCredentials $createdCredential)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedCredential', array($createdCredential));

        return parent::addCreatedCredential($createdCredential);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedCredential(\AppBundle\Entity\PageCredentials $createdCredential)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedCredential', array($createdCredential));

        return parent::removeCreatedCredential($createdCredential);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedCredentials', array());

        return parent::getCreatedCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedOrderProduct(\AppBundle\Entity\OrderProduct $createdOrderProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedOrderProduct', array($createdOrderProduct));

        return parent::addCreatedOrderProduct($createdOrderProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedOrderProduct(\AppBundle\Entity\OrderProduct $createdOrderProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedOrderProduct', array($createdOrderProduct));

        return parent::removeCreatedOrderProduct($createdOrderProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOrderProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOrderProducts', array());

        return parent::getCreatedOrderProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedPageCategory(\AppBundle\Entity\PageCategory $createdPageCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedPageCategory', array($createdPageCategory));

        return parent::addCreatedPageCategory($createdPageCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedPageCategory(\AppBundle\Entity\PageCategory $createdPageCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedPageCategory', array($createdPageCategory));

        return parent::removeCreatedPageCategory($createdPageCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedPageCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedPageCategories', array());

        return parent::getCreatedPageCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedPageType(\AppBundle\Entity\PageType $createdPageType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedPageType', array($createdPageType));

        return parent::addCreatedPageType($createdPageType);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedPageType(\AppBundle\Entity\PageType $createdPageType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedPageType', array($createdPageType));

        return parent::removeCreatedPageType($createdPageType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedPageTypes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedPageTypes', array());

        return parent::getCreatedPageTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedProductCategory(\AppBundle\Entity\ProductCategory $createdProductCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedProductCategory', array($createdProductCategory));

        return parent::addCreatedProductCategory($createdProductCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedProductCategory(\AppBundle\Entity\ProductCategory $createdProductCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedProductCategory', array($createdProductCategory));

        return parent::removeCreatedProductCategory($createdProductCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedProductCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedProductCategories', array());

        return parent::getCreatedProductCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedProductConnection(\AppBundle\Entity\ProductConnection $createdProductConnection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedProductConnection', array($createdProductConnection));

        return parent::addCreatedProductConnection($createdProductConnection);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedProductConnection(\AppBundle\Entity\ProductConnection $createdProductConnection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedProductConnection', array($createdProductConnection));

        return parent::removeCreatedProductConnection($createdProductConnection);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedProductConnections()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedProductConnections', array());

        return parent::getCreatedProductConnections();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedProductType(\AppBundle\Entity\ProductType $createdProductType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedProductType', array($createdProductType));

        return parent::addCreatedProductType($createdProductType);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedProductType(\AppBundle\Entity\ProductType $createdProductType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedProductType', array($createdProductType));

        return parent::removeCreatedProductType($createdProductType);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedProductTypes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedProductTypes', array());

        return parent::getCreatedProductTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedPayment(\AppBundle\Entity\Payment $createdPayment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedPayment', array($createdPayment));

        return parent::addCreatedPayment($createdPayment);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedPayment(\AppBundle\Entity\Payment $createdPayment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedPayment', array($createdPayment));

        return parent::removeCreatedPayment($createdPayment);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedPayments()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedPayments', array());

        return parent::getCreatedPayments();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedStatusHistory(\AppBundle\Entity\OrderStatusHistory $createdStatusHistory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedStatusHistory', array($createdStatusHistory));

        return parent::addCreatedStatusHistory($createdStatusHistory);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedStatusHistory(\AppBundle\Entity\OrderStatusHistory $createdStatusHistory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedStatusHistory', array($createdStatusHistory));

        return parent::removeCreatedStatusHistory($createdStatusHistory);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedStatusHistories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedStatusHistories', array());

        return parent::getCreatedStatusHistories();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedMessage(\AppBundle\Entity\Message $createdMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedMessage', array($createdMessage));

        return parent::addCreatedMessage($createdMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedMessage(\AppBundle\Entity\Message $createdMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedMessage', array($createdMessage));

        return parent::removeCreatedMessage($createdMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedMessages', array());

        return parent::getCreatedMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function addRecivedMessage(\AppBundle\Entity\Message $recivedMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRecivedMessage', array($recivedMessage));

        return parent::addRecivedMessage($recivedMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRecivedMessage(\AppBundle\Entity\Message $recivedMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRecivedMessage', array($recivedMessage));

        return parent::removeRecivedMessage($recivedMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecivedMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecivedMessages', array());

        return parent::getRecivedMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function addUpdatedMessage(\AppBundle\Entity\Message $updatedMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUpdatedMessage', array($updatedMessage));

        return parent::addUpdatedMessage($updatedMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpdatedMessage(\AppBundle\Entity\Message $updatedMessage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpdatedMessage', array($updatedMessage));

        return parent::removeUpdatedMessage($updatedMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedMessages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedMessages', array());

        return parent::getUpdatedMessages();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedGroup(\AppBundle\Entity\Group $createdGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedGroup', array($createdGroup));

        return parent::addCreatedGroup($createdGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedGroup(\AppBundle\Entity\Group $createdGroup)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedGroup', array($createdGroup));

        return parent::removeCreatedGroup($createdGroup);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedGroups', array());

        return parent::getCreatedGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedPost(\AppBundle\Entity\Post $createdPost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedPost', array($createdPost));

        return parent::addCreatedPost($createdPost);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedPost(\AppBundle\Entity\Post $createdPost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedPost', array($createdPost));

        return parent::removeCreatedPost($createdPost);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedPosts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedPosts', array());

        return parent::getCreatedPosts();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedMail(\AppBundle\Entity\Mail $createdMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedMail', array($createdMail));

        return parent::addCreatedMail($createdMail);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedMail(\AppBundle\Entity\Mail $createdMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedMail', array($createdMail));

        return parent::removeCreatedMail($createdMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedMails()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedMails', array());

        return parent::getCreatedMails();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedProduct(\AppBundle\Entity\Product $createdProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedProduct', array($createdProduct));

        return parent::addCreatedProduct($createdProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedProduct(\AppBundle\Entity\Product $createdProduct)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedProduct', array($createdProduct));

        return parent::removeCreatedProduct($createdProduct);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedProducts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedProducts', array());

        return parent::getCreatedProducts();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedOrderStatus(\AppBundle\Entity\OrderStatus $createdOrderStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedOrderStatus', array($createdOrderStatus));

        return parent::addCreatedOrderStatus($createdOrderStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedOrderStatus(\AppBundle\Entity\OrderStatus $createdOrderStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedOrderStatus', array($createdOrderStatus));

        return parent::removeCreatedOrderStatus($createdOrderStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOrderStatuses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOrderStatuses', array());

        return parent::getCreatedOrderStatuses();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedPage(\AppBundle\Entity\Page $createdPage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedPage', array($createdPage));

        return parent::addCreatedPage($createdPage);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedPage(\AppBundle\Entity\Page $createdPage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedPage', array($createdPage));

        return parent::removeCreatedPage($createdPage);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedPages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedPages', array());

        return parent::getCreatedPages();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedOrder(\AppBundle\Entity\Order $createdOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedOrder', array($createdOrder));

        return parent::addCreatedOrder($createdOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedOrder(\AppBundle\Entity\Order $createdOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedOrder', array($createdOrder));

        return parent::removeCreatedOrder($createdOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedOrders', array());

        return parent::getCreatedOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedAddress(\AppBundle\Entity\Address $createdAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedAddress', array($createdAddress));

        return parent::addCreatedAddress($createdAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedAddress(\AppBundle\Entity\Address $createdAddress)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedAddress', array($createdAddress));

        return parent::removeCreatedAddress($createdAddress);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAddresses()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAddresses', array());

        return parent::getCreatedAddresses();
    }

    /**
     * {@inheritDoc}
     */
    public function addCreatedUser(\AppBundle\Entity\User $createdUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCreatedUser', array($createdUser));

        return parent::addCreatedUser($createdUser);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCreatedUser(\AppBundle\Entity\User $createdUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCreatedUser', array($createdUser));

        return parent::removeCreatedUser($createdUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedUsers', array());

        return parent::getCreatedUsers();
    }

    /**
     * {@inheritDoc}
     */
    public function setProvision($provision)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProvision', array($provision));

        return parent::setProvision($provision);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvision', array());

        return parent::getProvision();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentPartnerCode($parentPartnerCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentPartnerCode', array($parentPartnerCode));

        return parent::setParentPartnerCode($parentPartnerCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentPartnerCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentPartnerCode', array());

        return parent::getParentPartnerCode();
    }

    /**
     * {@inheritDoc}
     */
    public function addParentPartnerOrder(\AppBundle\Entity\Order $parentPartnerOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addParentPartnerOrder', array($parentPartnerOrder));

        return parent::addParentPartnerOrder($parentPartnerOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function removeParentPartnerOrder(\AppBundle\Entity\Order $parentPartnerOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeParentPartnerOrder', array($parentPartnerOrder));

        return parent::removeParentPartnerOrder($parentPartnerOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentPartnerOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentPartnerOrders', array());

        return parent::getParentPartnerOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function addPartner(\AppBundle\Entity\User $partner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPartner', array($partner));

        return parent::addPartner($partner);
    }

    /**
     * {@inheritDoc}
     */
    public function removePartner(\AppBundle\Entity\User $partner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePartner', array($partner));

        return parent::removePartner($partner);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartners()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartners', array());

        return parent::getPartners();
    }

    /**
     * {@inheritDoc}
     */
    public function setParentPartner(\AppBundle\Entity\User $parentPartner = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setParentPartner', array($parentPartner));

        return parent::setParentPartner($parentPartner);
    }

    /**
     * {@inheritDoc}
     */
    public function getParentPartner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getParentPartner', array());

        return parent::getParentPartner();
    }

    /**
     * {@inheritDoc}
     */
    public function addPartnerOrder(\AppBundle\Entity\Order $partnerOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPartnerOrder', array($partnerOrder));

        return parent::addPartnerOrder($partnerOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function removePartnerOrder(\AppBundle\Entity\Order $partnerOrder)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePartnerOrder', array($partnerOrder));

        return parent::removePartnerOrder($partnerOrder);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartnerOrders()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartnerOrders', array());

        return parent::getPartnerOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function setAds($ads)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAds', array($ads));

        return parent::setAds($ads);
    }

    /**
     * {@inheritDoc}
     */
    public function getAds()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAds', array());

        return parent::getAds();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdsShow($adsShow)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdsShow', array($adsShow));

        return parent::setAdsShow($adsShow);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdsShow()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdsShow', array());

        return parent::getAdsShow();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdsName($adsName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdsName', array($adsName));

        return parent::setAdsName($adsName);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdsName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdsName', array());

        return parent::getAdsName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdsDescription($adsDescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdsDescription', array($adsDescription));

        return parent::setAdsDescription($adsDescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdsDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdsDescription', array());

        return parent::getAdsDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdMobile($adMobile)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdMobile', array($adMobile));

        return parent::setAdMobile($adMobile);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdMobile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdMobile', array());

        return parent::getAdMobile();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdDesktop($adDesktop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdDesktop', array($adDesktop));

        return parent::setAdDesktop($adDesktop);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdDesktop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdDesktop', array());

        return parent::getAdDesktop();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdLink($adLink)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdLink', array($adLink));

        return parent::setAdLink($adLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdLink()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdLink', array());

        return parent::getAdLink();
    }

    /**
     * {@inheritDoc}
     */
    public function addRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', array($role));

        return parent::addRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', array());

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', array($serialized));

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsernameCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsernameCanonical', array());

        return parent::getUsernameCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailCanonical', array());

        return parent::getEmailCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlainPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlainPassword', array());

        return parent::getPlainPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLogin', array());

        return parent::getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmationToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmationToken', array());

        return parent::getConfirmationToken();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function hasRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRole', array($role));

        return parent::hasRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonExpired', array());

        return parent::isAccountNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonLocked', array());

        return parent::isAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsNonExpired', array());

        return parent::isCredentialsNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsExpired', array());

        return parent::isCredentialsExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', array());

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function isExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExpired', array());

        return parent::isExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLocked', array());

        return parent::isLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isSuperAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSuperAdmin', array());

        return parent::isSuperAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', array($role));

        return parent::removeRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsernameCanonical($usernameCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsernameCanonical', array($usernameCanonical));

        return parent::setUsernameCanonical($usernameCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function setCredentialsExpireAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredentialsExpireAt', array($date));

        return parent::setCredentialsExpireAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setCredentialsExpired($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredentialsExpired', array($boolean));

        return parent::setCredentialsExpired($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', array($boolean));

        return parent::setEnabled($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setExpired($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpired', array($boolean));

        return parent::setExpired($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiresAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiresAt', array($date));

        return parent::setExpiresAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setSuperAdmin($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuperAdmin', array($boolean));

        return parent::setSuperAdmin($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setPlainPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlainPassword', array($password));

        return parent::setPlainPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLogin(\DateTime $time = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLogin', array($time));

        return parent::setLastLogin($time);
    }

    /**
     * {@inheritDoc}
     */
    public function setLocked($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocked', array($boolean));

        return parent::setLocked($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmationToken($confirmationToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmationToken', array($confirmationToken));

        return parent::setConfirmationToken($confirmationToken);
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordRequestedAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordRequestedAt', array($date));

        return parent::setPasswordRequestedAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordRequestedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordRequestedAt', array());

        return parent::getPasswordRequestedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isPasswordRequestNonExpired($ttl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPasswordRequestNonExpired', array($ttl));

        return parent::isPasswordRequestNonExpired($ttl);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', array($roles));

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroups', array());

        return parent::getGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupNames', array());

        return parent::getGroupNames();
    }

    /**
     * {@inheritDoc}
     */
    public function hasGroup($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasGroup', array($name));

        return parent::hasGroup($name);
    }

    /**
     * {@inheritDoc}
     */
    public function addGroup(\FOS\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGroup', array($group));

        return parent::addGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGroup(\FOS\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGroup', array($group));

        return parent::removeGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
