<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PageCredentials extends \AppBundle\Entity\PageCredentials implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\PageCredentials' . "\0" . 'id', 'page', 'family', 'type', 'creator', 'user', '' . "\0" . 'AppBundle\\Entity\\PageCredentials' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\PageCredentials' . "\0" . 'updated', 'page_edit', 'family_edit', 'page_image', 'page_background', 'page_images', 'page_audiobooks', 'page_remind', 'page_posts_delete', 'page_posts_notification');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\PageCredentials' . "\0" . 'id', 'page', 'family', 'type', 'creator', 'user', '' . "\0" . 'AppBundle\\Entity\\PageCredentials' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\PageCredentials' . "\0" . 'updated', 'page_edit', 'family_edit', 'page_image', 'page_background', 'page_images', 'page_audiobooks', 'page_remind', 'page_posts_delete', 'page_posts_notification');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PageCredentials $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', array($updated));

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', array());

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setPage(\AppBundle\Entity\Page $page = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPage', array($page));

        return parent::setPage($page);
    }

    /**
     * {@inheritDoc}
     */
    public function getPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPage', array());

        return parent::getPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreator(\AppBundle\Entity\User $creator = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreator', array($creator));

        return parent::setCreator($creator);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreator()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreator', array());

        return parent::getCreator();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\AppBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageEdit($pageEdit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageEdit', array($pageEdit));

        return parent::setPageEdit($pageEdit);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageEdit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageEdit', array());

        return parent::getPageEdit();
    }

    /**
     * {@inheritDoc}
     */
    public function setFamilyEdit($familyEdit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFamilyEdit', array($familyEdit));

        return parent::setFamilyEdit($familyEdit);
    }

    /**
     * {@inheritDoc}
     */
    public function getFamilyEdit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFamilyEdit', array());

        return parent::getFamilyEdit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageImage($pageImage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageImage', array($pageImage));

        return parent::setPageImage($pageImage);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageImage', array());

        return parent::getPageImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageBackground($pageBackground)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageBackground', array($pageBackground));

        return parent::setPageBackground($pageBackground);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageBackground()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageBackground', array());

        return parent::getPageBackground();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageImages($pageImages)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageImages', array($pageImages));

        return parent::setPageImages($pageImages);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageImages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageImages', array());

        return parent::getPageImages();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageAudiobooks($pageAudiobooks)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageAudiobooks', array($pageAudiobooks));

        return parent::setPageAudiobooks($pageAudiobooks);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageAudiobooks()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageAudiobooks', array());

        return parent::getPageAudiobooks();
    }

    /**
     * {@inheritDoc}
     */
    public function setPageRemind($pageRemind)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPageRemind', array($pageRemind));

        return parent::setPageRemind($pageRemind);
    }

    /**
     * {@inheritDoc}
     */
    public function getPageRemind()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPageRemind', array());

        return parent::getPageRemind();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagePostsDelete($pagePostsDelete)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagePostsDelete', array($pagePostsDelete));

        return parent::setPagePostsDelete($pagePostsDelete);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagePostsDelete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagePostsDelete', array());

        return parent::getPagePostsDelete();
    }

    /**
     * {@inheritDoc}
     */
    public function setPagePostsNotification($pagePostsNotification)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPagePostsNotification', array($pagePostsNotification));

        return parent::setPagePostsNotification($pagePostsNotification);
    }

    /**
     * {@inheritDoc}
     */
    public function getPagePostsNotification()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPagePostsNotification', array());

        return parent::getPagePostsNotification();
    }

    /**
     * {@inheritDoc}
     */
    public function setFamily(\AppBundle\Entity\Family $family = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFamily', array($family));

        return parent::setFamily($family);
    }

    /**
     * {@inheritDoc}
     */
    public function getFamily()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFamily', array());

        return parent::getFamily();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

}
