<?php

namespace AppBundle\Entity;

/**
 * PageCredentialsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageCredentialsRepository extends \Doctrine\ORM\EntityRepository
{
}
