<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getConnectedProducts($product)
    {
  
            $em = $this->getEntityManager();
            $query = $em->createQuery(
                'SELECT p FROM AppBundle:Product p
                JOIN AppBundle:ProductConnection c WITH (c.product = p OR  c.product_connected = p)  
                WHERE (c.product = :product OR c.product_connected = :product) AND p<>:product 
                GROUP BY p.id
                ORDER BY p.id ASC');
            $query->setParameter('product', $product);
            
            $products = $query->getResult();
        
            return $products;
    }  
}
